apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: speaker-01
  labels:
    description: 'Speaker'
    manufacturer: 'test'
spec:
  deviceModelRef:
    name: speaker-model
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: ''
            operator: In
            values:
              - raspberrypi
---
apiVersion: devices.kubeedge.io/v1alpha2
kind: DeviceModel
metadata:
  name: speaker-model
  namespace: default
spec:
  properties:
    - name: track
      description: music track to play
      type:
        string:
          accessMode: ReadWrite
          defaultValue: ''