apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: kubeedge-wechat-app
  name: kubeedge-wechat-app
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: kubeedge-wechat-app
  template:
    metadata:
      labels:
        k8s-app: kubeedge-wechat-app
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      hostNetwork: true
      containers:
        - name: kubeedge-wechat-app
          image: prodan/kubeedge-wechat-app:latest
          env:
          - name: SERVER_ADDR_PORT
            value: "xxx.xxx.xxx:443"
          - name: WECHAT_APP_ID
            value: "xxx"
          - name: WECHAT_APP_SECRET
            value: "xxx.xxx.xxx:443"
          - name: WECHAT_TOKEN
            value: "xxxx"
          - name: WECHAT_ENCODING_AES_KEY
            value: "xxx.xxx.xxx:443"
          - name: IN_CLUSTER
            value: "in-cluster"
          - name: DEVICE_ID
            value: "speaker-01"
          - name: DEVICE_NAMESPACE
            value: "default"
      restartPolicy: Always
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: kubeedge-wechat-app
  namespace: default
rules:
  - apiGroups: ["devices.kubeedge.io"]
    resources: ["devices"]
    verbs: ["get", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: kubeedge-wechat-app-rbac
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: kubeedge-wechat-app
  apiGroup: rbac.authorization.k8s.io